### ISSUE TITLE
night and normal background color not working.

### ISSUE THREAD

**Issue by commando24** [Draveness/NightNight#16]
I am setting night background and normal background color in storyboard but its not working.
I tried to print property mixedBackgroundColor of view but it shows nil.

**Comment by commando24** [comment]
I found a solution for this situation. 
```
extension UIView {
  
  open override func awakeFromNib() {
    super.awakeFromNib()
    
    if let normalBackgroundColor = self.normalBackgroundColor, let nightBackgroundColor = self.nightBackgroundColor {
        self.mixedBackgroundColor = MixedColor(normal: normalBackgroundColor, night: nightBackgroundColor)
    }
  }
}
```
anyone have other solution ?

**Comment by Draveness** [comment]
not supported storyboard yet and may not supported neither in the future
