### ISSUE TITLE
How to switch the color of buttonBarBackgroundColor using XLPagerTabStrip

### ISSUE THREAD

**Issue by tomoya92** [draveness/NightNight#33]
self.settings.style.buttonBarBackgroundColor don't have mixedBackgroundColor , so i use it 

```swift
        if NightNight.theme == .normal {
            self.settings.style.buttonBarBackgroundColor = UIColor(CNodeColor.backgroundColor)
            self.settings.style.buttonBarItemBackgroundColor = UIColor(CNodeColor.backgroundColor)
        } else {
            self.settings.style.buttonBarBackgroundColor = UIColor(CNodeColor.backgroundColor_dark)
            self.settings.style.buttonBarItemBackgroundColor = UIColor(CNodeColor.backgroundColor_dark)
        }
```

when i execute `NightNight.theme = .night` It has not changed.

In addition 

how to use NightNightThemeChangeNotification ? Can you give a demo ?

**Comment by robert-cronin** [comment]
is this repository maintained anymore? There is also no mixedTintColor for tintColor of UIButton. 
Also @tomoya92 you wouldn't be seeing any change because it's not reactive
